### ISSUE TITLE
Support SAML SSO authentication method

### ISSUE THREAD

**Issue by vostrom** [dm-drogeriemarkt/Email-to-Confluence#15]
**Type**: Feature
-------------------
#### Description
My exchange doesn't support user+password authentication but a SAML SSO + Active Directory + LDAP for sign on. I really need the plugin to be able to authenticate in this method..

Thanks!
#### Proposal
Add SAML SSO authentication support

**Comment by gellweiler** [comment]
I'm sorry but SAML SSO authentication support is a feature not planned for this add-on. You are welcome to implement the feature of course and to create a pull request.
If your confluence page has internet access you might use an external mail provider like gmail and setup forwarding of emails with an exchange rule.
