### ISSUE TITLE
Lost emails

### ISSUE THREAD

**Issue by Richardb953** [dm-drogeriemarkt/Email-to-Confluence#4]
**Version**:  Last one
**Type**: Question

-------------------
#### Description
I Connect plugin to my mail client from latest confluence and some mails was created in Confluence in blog section unfortunately I lost all my emails in my mail client... Mails are not in trash, not in received package. 

Update: I found mails in new folder: Invalid. Please inform about this in documentation I was really scared where all my mails are. Yours plugin is creating this package in mail clients and move there all emails which are with unsupported subject

**Comment by gellweiler** [comment]
I will update the UI to be more clear on this. Just for reference:

If you’re using POP3 the default behavior is to delete processed emails. This is why there is a Warning Label above the selection. If you used POP3 there really is little you can do. Unless you have a second email app on your mobile or some where else that mirrors emails. If you used IMAP the emails get moved to different folders below your INBOX: INBOX/Processed and INBOX/Invalid some E-Mail clients won’t show those folders, unless you add them manually or there difficult to spot. Best one does a online search for your e-mail client/provider.

**Comment by gellweiler** [comment]
Just for reference, the next release will have the following on the configuration page:

![screen shot 2018-03-22 at 18 53 29](https://user-images.githubusercontent.com/3253331/37788700-6a46d618-2e02-11e8-8d65-3a5ed3b49134.png)
<img width="878" alt="screen shot 2018-03-22 at 18 51 11" src="https://user-images.githubusercontent.com/3253331/37788701-6a67157c-2e02-11e8-977c-0058da3b9e36.png">
