### ISSUE TITLE
Incomplete warning info logged for exceptions with null value returned for getMessage()

### ISSUE THREAD

**Issue by jad359** [dm-drogeriemarkt/Email-to-Confluence#5]
**Version**: most recent
**Type**: Bug

-------------------
#### Description
Incomplete info logged in warning message when `getSpaces` in `SpaceExtractor` encounters an exception with `null` value returned for `getMessage()`. It would be useful to include the entire `toString` of the exception, the exception type, the stack trace, etc., instead of simply logging `Exception(null)`. The exception message can be null in cases like NullPointerException, for example.

#### Expected Behavior
Logged warning: ` [de.dm.mail2blog.SpaceExtractor] getSpaces Mail2Blog: Exception(the exception's toString representation, stack trace, or something useful) for SpaceRule{"field":"to/cc","operator":"is","value":"*****@*****.com","action":"move","space":"SE","contentType":"page"}`

#### Actual Behavior
Logged warning: `[de.dm.mail2blog.SpaceExtractor] getSpaces Mail2Blog: Exception(null) for SpaceRule{"field":"to/cc","operator":"is","value":"*****@*****.com","action":"move","space":"SE","contentType":"page"}`

**Comment by gellweiler** [comment]
Yeah your right. The log messages need some overhauling. I'm going to do this during the cause of this week. Did you experience any other issues that caused the logging message? My guess would be the space doesn't exist anymore.

**Comment by jad359** [comment]
Yes, currently all emails end up in our default space despite the 3 rules we have created. We are still trying to debug that. The space does exist but has restricted permissions, which I'm thinking we might need to reconfigure in some way.

**Comment by gellweiler** [comment]
OK I have fixed the issue. The problem was, that there was no check for a missing CC header for TO/CC. Sorry for the late reply.

**Comment by jad359** [comment]
Thanks, much appreciated!
