### ISSUE TITLE
Emails not fetched from the mailbox though authenticated successfully

### ISSUE THREAD

**Issue by KesavaBharathi** [dm-drogeriemarkt/Email-to-Confluence#9]
**Version**: 2.0
**Type**: Bug

-------------------
#### Description
I am using the v2.0 of the add-on and it stopped fetching emails from the mailbox. When i save the configuration, it saves it successfully. Please help me resolve the issue.

**Comment by gellweiler** [comment]
Without more information it is going to be hard to resolve this issue. Your [log file](https://confluence.atlassian.com/doc/working-with-confluence-logs-108364721.html) might give more insight to your issue. If you want to you email me your logfile to `mail2blog.dmDeutschland@dm.de` and I might take a look at it.

**Comment by KesavaBharathi** [comment]
The issue is actually with the scheduler job that this add-on is using. Looks like it works when we manually run it and not automatically. Can you please help?

**Comment by gellweiler** [comment]
Hmm, I've manually tested it on Confluence 6.12 and I've updated the integration test to include testing the scheduler (and run that against Confluence 6.6.6 and Confluence 5.10.9). Without more information I can not determine, why it is not working for you. So this is why I'm closing it for now, unsless you can provide more information.
